// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPOwNuScepFy1BoLEUQRjApFq1hM_GUHI',
    appId: '1:249613703605:web:2c6a711d8b44d6ee6161fc',
    messagingSenderId: '249613703605',
    projectId: 'task-manager-5df79',
    authDomain: 'task-manager-5df79.firebaseapp.com',
    storageBucket: 'task-manager-5df79.firebasestorage.app',
    measurementId: 'G-5E9HES5LX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQojUxIyKuYsJJ_PU_iQPdzqqLdi1Goo',
    appId: '1:249613703605:android:166ee3a2a3c8cb056161fc',
    messagingSenderId: '249613703605',
    projectId: 'task-manager-5df79',
    storageBucket: 'task-manager-5df79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg3cToVPE97hqEr2b9WMe-V0RIz_kZZbo',
    appId: '1:249613703605:ios:820d24640f383c336161fc',
    messagingSenderId: '249613703605',
    projectId: 'task-manager-5df79',
    storageBucket: 'task-manager-5df79.firebasestorage.app',
    iosBundleId: 'com.example.djamoTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg3cToVPE97hqEr2b9WMe-V0RIz_kZZbo',
    appId: '1:249613703605:ios:820d24640f383c336161fc',
    messagingSenderId: '249613703605',
    projectId: 'task-manager-5df79',
    storageBucket: 'task-manager-5df79.firebasestorage.app',
    iosBundleId: 'com.example.djamoTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPOwNuScepFy1BoLEUQRjApFq1hM_GUHI',
    appId: '1:249613703605:web:d3a2f43e4a8334306161fc',
    messagingSenderId: '249613703605',
    projectId: 'task-manager-5df79',
    authDomain: 'task-manager-5df79.firebaseapp.com',
    storageBucket: 'task-manager-5df79.firebasestorage.app',
    measurementId: 'G-XXMV9J5Y95',
  );
}
